[project]
name = "rignore"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
version = "0.8.1"
description = "Python Bindings for the ignore crate"
authors = [
    {name = "Patrick Arminio", email = "patrick.arminio@gmail.com"},
]
dependencies = []
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["maturin>=1.14.1,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.autopub]
git-username = "github-actions[bot]"
git-email = "41898282+github-actions[bot]@users.noreply.github.com"
plugins = [
    "autopub.plugins.github",
    "scripts.autopub_rignore",
]

[dependency-groups]
dev = [
    "pytest>=8.2.2",
    "typing-extensions>=4.12.2",
    "maturin>=1.14.1",
    "inline-snapshot>=0.29.2",
    "pytest-cov",
    "coverage",
]

[tool.coverage.run]
branch = true
source = ["rignore"]
parallel = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "@abstractmethod",
]

[tool.coverage.html]
directory = "htmlcov"
